DROP TABLE IF EXISTS moods CASCADE;

CREATE TABLE
  moods (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    date_added DATE DEFAULT CURRENT_DATE
  );